#!/usr/bin/env python3
import json
import sys
from pathlib import Path

MANIFEST_PATH = Path("word_manifest.json")
OUTPUT_C_PATH = Path("src/dictionary_data.c")

def generate_dictionary():
    if not MANIFEST_PATH.exists():
        print(f"Error: Manifest missing at {MANIFEST_PATH}")
        sys.exit(1)

    with open(MANIFEST_PATH, "r", encoding="utf-8") as f:
        manifest = json.load(f)
    
    string_table_bytes = bytearray()
    word_entries = []
    
    for i, entry in enumerate(manifest):
        word = entry["word"]
        definition = entry.get("definition", "")
        
        def_offset = len(string_table_bytes)
        string_table_bytes.extend(definition.encode("utf-8"))
        string_table_bytes.append(0)
        
        word_entries.append(f'    {{ "{word}", {i}, {def_offset} }}')

    # bytearray(b"...") is 12 chars from the start and two chars at the end
    # replace \x00 with \000 because \x00 bleeds into next letter if valid hex
    formatted_string_table = repr(string_table_bytes)[12:-2].replace(r"\x00",r"\000")

    word_count = len(word_entries)
    entries_formatted = ",\n".join(word_entries)
    
    c_content = f"""// Generated by tools/generate_dictionary.py
#include "dictionary_data.h"

static const char g_def_string_table[] = "{formatted_string_table}";

static const word_entry_t g_dictionary_words[{word_count}] = {{
{entries_formatted}
}};

const dictionary_db_t g_dictionary = {{
    .word_count = {word_count},
    .words = g_dictionary_words,
    .def_string_table = g_def_string_table
}};
"""

    OUTPUT_C_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_C_PATH, "w", encoding="utf-8") as f:
        f.write(c_content)
    
    print(f"C database successfully generated at {OUTPUT_C_PATH}")

if __name__ == "__main__": generate_dictionary()